<a href="https://colab.research.google.com/github/julianox5/Desafios-Resolvidos-do-curso-machine-learning-crash-course-google/blob/master/numpy_para_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importando o numpy

In [0]:
import numpy as np

## Preencher matrizes com números expecíficos

Criando uma matriz com o numpy.array()

In [0]:
myArray = np.array([1,2,3,4,5,6,7,8,9,0])
print(myArray)

[1 2 3 4 5 6 7 8 9 0]


Criando uma matriz bidimensional 3 x 2

In [0]:
matriz_bi = np.array([[6 , 5], [11 , 4], [5 , 9] ])
print(matriz_bi)

[[ 6  5]
 [11  4]
 [ 5  9]]


Prencher um matriz com uma sequência de numeros, numpy.arange()

In [0]:
metodArange = np.arange(5, 12)
print(metodArange)

[ 5  6  7  8  9 10 11]


## Preencher matrizes com sequência de números
Numpy possui varias funções para preencher matrizes com números aleatórios em determinados intervalos.
***numpy.random.randint*** gera números inteiros aleatórios entre um valor baixo e alto.

In [0]:
aleatorio_randint = np.random.randint(low = 10, high=100, size=(10))
print(aleatorio_randint)

[39 82 57 89 69 43 96 45 21 56]


Criar valores aleatórios de ponto flutuante entre 0,0 e 1,0 use **numpy.random.random()**

In [0]:
float_random = np.random.random([10])
print(float_random)

[0.25235296 0.08061505 0.03279996 0.59767375 0.27453448 0.31184018
 0.17296004 0.6211853  0.01678728 0.4507196 ]


O Numpy possui um truque chamado broadcasting que expande virtualmente o operando menor para dimensões compatíveis com a álgebra linear. 

In [0]:
random_floats_2_e_3 = float_random + 2.0
print (random_floats_2_e_3)

[2.25235296 2.08061505 2.03279996 2.59767375 2.27453448 2.31184018
 2.17296004 2.6211853  2.01678728 2.4507196 ]


## Tarefa 1: Criar um conjunto de dados linear
Seu objetivo é criar um conjunto de dados simples que consiste em um único recurso e um rótulo da seguinte maneira:
1. Atribua uma sequência de números inteiros de 6 a 20 (inclusive) a uma matriz NumPy denominada `feature`.
2.Atribua 15 valores a uma matriz NumPy denominada de labelmodo que:

```
   label = (3)(feature) + 4
```
Por exemplo, o primeiro valor para `label`deve ser:

```
  label = (3)(6) + 4 = 22
 ```

In [0]:
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]



## Tarefa 2: adicionar algum ruído ao conjunto de dados

Para tornar seu conjunto de dados um pouco mais realista, insira um pouco de ruído aleatório em cada elemento da labelmatriz que você já criou. Para ser mais preciso, modifique cada valor atribuído rótulo, adicionando um valor de ponto flutuante aleatório diferente entre -2 e +2.

ão confie na transmissão. Em vez disso, crie um ruido na matriz com a mesma dimensão que rótulo.

In [0]:
noise = (np.random.random([15]) * 4) -2
print(noise)
label += noise 
print(label)

[-0.2195936   1.3326103   1.84731153 -0.2603278  -1.46650376 -0.45077214
 -0.08141228 -0.59877044 -0.39544639  1.06051902 -0.3939568  -0.34886473
  0.94562907  1.45291256 -0.09328554]


UFuncTypeError: ignored

In [0]:
#@title Example form fields
#@markdown Forms support many types of fields.

no_type_checking = ''  #@param
string_type = 'example'  #@param {type: "string"}
slider_value = 142  #@param {type: "slider", min: 100, max: 200}
number = 102  #@param {type: "number"}
date = '2010-11-05'  #@param {type: "date"}
pick_me = "monday"  #@param ['monday', 'tuesday', 'wednesday', 'thursday']
select_or_input = "apples" #@param ["apples", "bananas", "oranges"] {allow-input: true}
#@markdown ---
